#############################################################################
# Makefile for building: release/gbcflsh.app/Contents/MacOS/gbcflsh
# Generated by qmake (3.1) (Qt 5.12.1)
# Project:  gbcf.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile gbcf.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include/libftdi1/ -I. -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -Ibuild -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers/ -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.12.1/lib
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = gbcflsh1.0.0
DISTDIR = /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/gbcflsh1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.12.1/lib -L/usr/local/lib -lftdi1 -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/About.cpp \
		src/EraseThread.cpp \
		src/gbcflsh.cpp \
		src/Gui.cpp \
		src/Logic.cpp \
		src/ReadFlashThread.cpp \
		src/ReadRamThread.cpp \
		src/Settings.cpp \
		src/WriteFlashThread.cpp \
		src/WriteRamThread.cpp \
		src/USBPortMac.cpp build/moc_About.cpp \
		build/moc_AbstractPort.cpp \
		build/moc_EraseThread.cpp \
		build/moc_Gui.cpp \
		build/moc_Logic.cpp \
		build/moc_ReadFlashThread.cpp \
		build/moc_ReadRamThread.cpp \
		build/moc_Settings.cpp \
		build/moc_WriteFlashThread.cpp \
		build/moc_WriteRamThread.cpp \
		build/moc_USBPortMac.cpp
OBJECTS       = build/About.o \
		build/EraseThread.o \
		build/gbcflsh.o \
		build/Gui.o \
		build/Logic.o \
		build/ReadFlashThread.o \
		build/ReadRamThread.o \
		build/Settings.o \
		build/WriteFlashThread.o \
		build/WriteRamThread.o \
		build/USBPortMac.o \
		build/moc_About.o \
		build/moc_AbstractPort.o \
		build/moc_EraseThread.o \
		build/moc_Gui.o \
		build/moc_Logic.o \
		build/moc_ReadFlashThread.o \
		build/moc_ReadRamThread.o \
		build/moc_Settings.o \
		build/moc_WriteFlashThread.o \
		build/moc_WriteRamThread.o \
		build/moc_USBPortMac.o
DIST          = /usr/local/Cellar/qt/5.12.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/spec_post.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/lex.prf \
		gbcf.pro src/About.h \
		src/AbstractPort.h \
		src/Console.h \
		src/const.h \
		src/EraseThread.h \
		src/Gui.h \
		src/Logic.h \
		src/ReadFlashThread.h \
		src/ReadRamThread.h \
		src/Settings.h \
		src/WriteFlashThread.h \
		src/WriteRamThread.h \
		src/about.xpm \
		src/flasher.xpm \
		src/icon.xpm \
		src/USBPortMac.h src/About.cpp \
		src/EraseThread.cpp \
		src/gbcflsh.cpp \
		src/Gui.cpp \
		src/Logic.cpp \
		src/ReadFlashThread.cpp \
		src/ReadRamThread.cpp \
		src/Settings.cpp \
		src/WriteFlashThread.cpp \
		src/WriteRamThread.cpp \
		src/USBPortMac.cpp
QMAKE_TARGET  = gbcflsh
DESTDIR       = release/
TARGET        = release/gbcflsh.app/Contents/MacOS/gbcflsh

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/gbcf.pro


include /usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

release/gbcflsh.app/Contents/MacOS/gbcflsh:  $(OBJECTS)  
	@test -d release/gbcflsh.app/Contents/MacOS/ || mkdir -p release/gbcflsh.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gbcf.pro /usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.12.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/spec_post.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.12.1/mkspecs/features/lex.prf \
		gbcf.pro \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile gbcf.pro
/usr/local/Cellar/qt/5.12.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.12.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.12.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.12.1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.12.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.12.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.12.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.12.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.12.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/spec_post.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.12.1/mkspecs/features/lex.prf:
gbcf.pro:
/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile gbcf.pro

qmake_all: FORCE

release/gbcflsh.app/Contents/PkgInfo: 
	@test -d release/gbcflsh.app/Contents || mkdir -p release/gbcflsh.app/Contents
	@$(DEL_FILE) release/gbcflsh.app/Contents/PkgInfo
	@echo "APPL????" > release/gbcflsh.app/Contents/PkgInfo
release/gbcflsh.app/Contents/Resources/empty.lproj: 
	@test -d release/gbcflsh.app/Contents/Resources || mkdir -p release/gbcflsh.app/Contents/Resources
	@touch release/gbcflsh.app/Contents/Resources/empty.lproj
	
release/gbcflsh.app/Contents/Info.plist: 
	@test -d release/gbcflsh.app/Contents || mkdir -p release/gbcflsh.app/Contents
	@$(DEL_FILE) release/gbcflsh.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.gbcflsh,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.gbcflsh,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,res.rc,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},res.rc,g" -e "s,@EXECUTABLE@,gbcflsh,g" -e "s,@LIBRARY@,gbcflsh,g" -e "s,\$${EXECUTABLE_NAME},gbcflsh,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang/Info.plist.app >release/gbcflsh.app/Contents/Info.plist
release/gbcflsh.app/Contents/Resources/res.rc: src/res.rc
	@test -d release/gbcflsh.app/Contents/Resources/ || mkdir -p release/gbcflsh.app/Contents/Resources/
	@$(DEL_FILE) release/gbcflsh.app/Contents/Resources/res.rc
	@$(COPY_FILE) src/res.rc release/gbcflsh.app/Contents/Resources/res.rc

all: Makefile \
		release/gbcflsh.app/Contents/PkgInfo \
		release/gbcflsh.app/Contents/Resources/empty.lproj \
		release/gbcflsh.app/Contents/Info.plist \
		release/gbcflsh.app/Contents/Resources/res.rc release/gbcflsh.app/Contents/MacOS/gbcflsh

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.12.1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/About.h src/AbstractPort.h src/Console.h src/const.h src/EraseThread.h src/Gui.h src/Logic.h src/ReadFlashThread.h src/ReadRamThread.h src/Settings.h src/WriteFlashThread.h src/WriteRamThread.h src/about.xpm src/flasher.xpm src/icon.xpm src/USBPortMac.h $(DISTDIR)/
	$(COPY_FILE) --parents src/About.cpp src/EraseThread.cpp src/gbcflsh.cpp src/Gui.cpp src/Logic.cpp src/ReadFlashThread.cpp src/ReadRamThread.cpp src/Settings.cpp src/WriteFlashThread.cpp src/WriteRamThread.cpp src/USBPortMac.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/gbcflsh_english.ts src/gbcflsh_french.ts src/gbcflsh_german.ts src/gbcflsh_polish.ts src/gbcflsh_japanese.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r release/gbcflsh.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc_predefs.h
build/moc_predefs.h: /usr/local/Cellar/qt/5.12.1/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o build/moc_predefs.h /usr/local/Cellar/qt/5.12.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc_About.cpp build/moc_AbstractPort.cpp build/moc_EraseThread.cpp build/moc_Gui.cpp build/moc_Logic.cpp build/moc_ReadFlashThread.cpp build/moc_ReadRamThread.cpp build/moc_Settings.cpp build/moc_WriteFlashThread.cpp build/moc_WriteRamThread.cpp build/moc_USBPortMac.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_About.cpp build/moc_AbstractPort.cpp build/moc_EraseThread.cpp build/moc_Gui.cpp build/moc_Logic.cpp build/moc_ReadFlashThread.cpp build/moc_ReadRamThread.cpp build/moc_Settings.cpp build/moc_WriteFlashThread.cpp build/moc_WriteRamThread.cpp build/moc_USBPortMac.cpp
build/moc_About.cpp: src/About.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QBoxLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		build/moc_predefs.h \
		/usr/local/Cellar/qt/5.12.1/bin/moc
	/usr/local/Cellar/qt/5.12.1/bin/moc $(DEFINES) --include /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/moc_predefs.h -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/include/libftdi1 -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.12.1/lib src/About.h -o build/moc_About.cpp

build/moc_AbstractPort.cpp: src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		build/moc_predefs.h \
		/usr/local/Cellar/qt/5.12.1/bin/moc
	/usr/local/Cellar/qt/5.12.1/bin/moc $(DEFINES) --include /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/moc_predefs.h -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/include/libftdi1 -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.12.1/lib src/AbstractPort.h -o build/moc_AbstractPort.cpp

build/moc_EraseThread.cpp: src/EraseThread.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Logic.h \
		src/const.h \
		build/moc_predefs.h \
		/usr/local/Cellar/qt/5.12.1/bin/moc
	/usr/local/Cellar/qt/5.12.1/bin/moc $(DEFINES) --include /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/moc_predefs.h -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/include/libftdi1 -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.12.1/lib src/EraseThread.h -o build/moc_EraseThread.cpp

build/moc_Gui.cpp: src/Gui.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QProgressBar \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qprogressbar.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Settings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/const.h \
		src/Console.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qcolor.h \
		src/Logic.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		src/AbstractPort.h \
		src/About.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QBoxLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		src/ReadFlashThread.h \
		src/WriteFlashThread.h \
		src/EraseThread.h \
		src/ReadRamThread.h \
		src/WriteRamThread.h \
		build/moc_predefs.h \
		/usr/local/Cellar/qt/5.12.1/bin/moc
	/usr/local/Cellar/qt/5.12.1/bin/moc $(DEFINES) --include /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/moc_predefs.h -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/include/libftdi1 -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.12.1/lib src/Gui.h -o build/moc_Gui.cpp

build/moc_Logic.cpp: src/Logic.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		src/const.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		build/moc_predefs.h \
		/usr/local/Cellar/qt/5.12.1/bin/moc
	/usr/local/Cellar/qt/5.12.1/bin/moc $(DEFINES) --include /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/moc_predefs.h -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/include/libftdi1 -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.12.1/lib src/Logic.h -o build/moc_Logic.cpp

build/moc_ReadFlashThread.cpp: src/ReadFlashThread.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Logic.h \
		src/const.h \
		build/moc_predefs.h \
		/usr/local/Cellar/qt/5.12.1/bin/moc
	/usr/local/Cellar/qt/5.12.1/bin/moc $(DEFINES) --include /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/moc_predefs.h -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/include/libftdi1 -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.12.1/lib src/ReadFlashThread.h -o build/moc_ReadFlashThread.cpp

build/moc_ReadRamThread.cpp: src/ReadRamThread.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Logic.h \
		src/const.h \
		build/moc_predefs.h \
		/usr/local/Cellar/qt/5.12.1/bin/moc
	/usr/local/Cellar/qt/5.12.1/bin/moc $(DEFINES) --include /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/moc_predefs.h -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/include/libftdi1 -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.12.1/lib src/ReadRamThread.h -o build/moc_ReadRamThread.cpp

build/moc_Settings.cpp: src/Settings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/const.h \
		build/moc_predefs.h \
		/usr/local/Cellar/qt/5.12.1/bin/moc
	/usr/local/Cellar/qt/5.12.1/bin/moc $(DEFINES) --include /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/moc_predefs.h -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/include/libftdi1 -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.12.1/lib src/Settings.h -o build/moc_Settings.cpp

build/moc_WriteFlashThread.cpp: src/WriteFlashThread.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Logic.h \
		src/const.h \
		build/moc_predefs.h \
		/usr/local/Cellar/qt/5.12.1/bin/moc
	/usr/local/Cellar/qt/5.12.1/bin/moc $(DEFINES) --include /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/moc_predefs.h -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/include/libftdi1 -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.12.1/lib src/WriteFlashThread.h -o build/moc_WriteFlashThread.cpp

build/moc_WriteRamThread.cpp: src/WriteRamThread.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Logic.h \
		src/const.h \
		build/moc_predefs.h \
		/usr/local/Cellar/qt/5.12.1/bin/moc
	/usr/local/Cellar/qt/5.12.1/bin/moc $(DEFINES) --include /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/moc_predefs.h -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/include/libftdi1 -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.12.1/lib src/WriteRamThread.h -o build/moc_WriteRamThread.cpp

build/moc_USBPortMac.cpp: src/USBPortMac.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		build/moc_predefs.h \
		/usr/local/Cellar/qt/5.12.1/bin/moc
	/usr/local/Cellar/qt/5.12.1/bin/moc $(DEFINES) --include /Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi/build/moc_predefs.h -I/usr/local/Cellar/qt/5.12.1/mkspecs/macx-clang -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/include/libftdi1 -I/Users/daviddegraw/Desktop/gbcartflasher-master/gbcflsh_1.1_libftdi -I/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.12.1/lib src/USBPortMac.h -o build/moc_USBPortMac.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/About.o: src/About.cpp src/About.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QBoxLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		src/about.xpm \
		src/const.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/About.o src/About.cpp

build/EraseThread.o: src/EraseThread.cpp src/EraseThread.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Logic.h \
		src/const.h \
		src/Settings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcheckbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/EraseThread.o src/EraseThread.cpp

build/gbcflsh.o: src/gbcflsh.cpp /usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QTranslator \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qtranslator.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QFileInfo \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qfileinfo.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QTextCodec \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qtextcodec.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		src/Gui.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QProgressBar \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qprogressbar.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Settings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/const.h \
		src/Console.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qcolor.h \
		src/Logic.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		src/AbstractPort.h \
		src/About.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QBoxLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		src/ReadFlashThread.h \
		src/WriteFlashThread.h \
		src/EraseThread.h \
		src/ReadRamThread.h \
		src/WriteRamThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/gbcflsh.o src/gbcflsh.cpp

build/Gui.o: src/Gui.cpp /usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QFileDialog \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/Gui.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QProgressBar \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qprogressbar.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Settings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcheckbox.h \
		src/const.h \
		src/Console.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qcolor.h \
		src/Logic.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		src/AbstractPort.h \
		src/About.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QBoxLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		src/ReadFlashThread.h \
		src/WriteFlashThread.h \
		src/EraseThread.h \
		src/ReadRamThread.h \
		src/WriteRamThread.h \
		src/USBPort.h \
		src/USBPortMac.h \
		src/USBPortWin.h \
		src/flasher.xpm \
		src/icon.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Gui.o src/Gui.cpp

build/Logic.o: src/Logic.cpp src/Logic.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		src/const.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Logic.o src/Logic.cpp

build/ReadFlashThread.o: src/ReadFlashThread.cpp src/ReadFlashThread.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Logic.h \
		src/const.h \
		src/Settings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcheckbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ReadFlashThread.o src/ReadFlashThread.cpp

build/ReadRamThread.o: src/ReadRamThread.cpp src/ReadRamThread.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Logic.h \
		src/const.h \
		src/Settings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcheckbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ReadRamThread.o src/ReadRamThread.cpp

build/Settings.o: src/Settings.cpp /usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QCoreApplication \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qcoreapplication.h \
		src/Settings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/const.h \
		src/Gui.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QProgressBar \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qprogressbar.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		src/Console.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qcolor.h \
		src/Logic.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		src/AbstractPort.h \
		src/About.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/Cellar/qt/5.12.1/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QBoxLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		src/ReadFlashThread.h \
		src/WriteFlashThread.h \
		src/EraseThread.h \
		src/ReadRamThread.h \
		src/WriteRamThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Settings.o src/Settings.cpp

build/WriteFlashThread.o: src/WriteFlashThread.cpp src/WriteFlashThread.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Logic.h \
		src/const.h \
		src/Settings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcheckbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/WriteFlashThread.o src/WriteFlashThread.cpp

build/WriteRamThread.o: src/WriteRamThread.cpp src/WriteRamThread.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Logic.h \
		src/const.h \
		src/Settings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcheckbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/WriteRamThread.o src/WriteRamThread.cpp

build/USBPortMac.o: src/USBPortMac.cpp src/const.h \
		src/USBPortMac.h \
		src/AbstractPort.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qstring.h \
		src/Settings.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.12.1/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.12.1/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/USBPortMac.o src/USBPortMac.cpp

build/moc_About.o: build/moc_About.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_About.o build/moc_About.cpp

build/moc_AbstractPort.o: build/moc_AbstractPort.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_AbstractPort.o build/moc_AbstractPort.cpp

build/moc_EraseThread.o: build/moc_EraseThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_EraseThread.o build/moc_EraseThread.cpp

build/moc_Gui.o: build/moc_Gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_Gui.o build/moc_Gui.cpp

build/moc_Logic.o: build/moc_Logic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_Logic.o build/moc_Logic.cpp

build/moc_ReadFlashThread.o: build/moc_ReadFlashThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ReadFlashThread.o build/moc_ReadFlashThread.cpp

build/moc_ReadRamThread.o: build/moc_ReadRamThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ReadRamThread.o build/moc_ReadRamThread.cpp

build/moc_Settings.o: build/moc_Settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_Settings.o build/moc_Settings.cpp

build/moc_WriteFlashThread.o: build/moc_WriteFlashThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_WriteFlashThread.o build/moc_WriteFlashThread.cpp

build/moc_WriteRamThread.o: build/moc_WriteRamThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_WriteRamThread.o build/moc_WriteRamThread.cpp

build/moc_USBPortMac.o: build/moc_USBPortMac.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_USBPortMac.o build/moc_USBPortMac.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

